# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import videoindexer
from videoindexer.api.languages_api import LanguagesApi  # noqa: E501
from videoindexer.rest import ApiException


class TestLanguagesApi(unittest.TestCase):
    """LanguagesApi unit test stubs"""

    def setUp(self):
        self.api = LanguagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_training_model(self):
        """Test case for cancel_training_model

        Cancel Training Model  # noqa: E501
        """
        pass

    def test_create_language_model(self):
        """Test case for create_language_model

        Create Language Model  # noqa: E501
        """
        pass

    def test_delete_language_model(self):
        """Test case for delete_language_model

        Delete Language Model  # noqa: E501
        """
        pass

    def test_delete_language_model_file(self):
        """Test case for delete_language_model_file

        Delete Language Model File  # noqa: E501
        """
        pass

    def test_download_language_model_file_content(self):
        """Test case for download_language_model_file_content

        Download Language Model File Content  # noqa: E501
        """
        pass

    def test_get_language_model(self):
        """Test case for get_language_model

        Get Language Model  # noqa: E501
        """
        pass

    def test_get_language_model_edits_history(self):
        """Test case for get_language_model_edits_history

        Get Language Model Edits History (PREVIEW)  # noqa: E501
        """
        pass

    def test_get_language_model_file_data(self):
        """Test case for get_language_model_file_data

        Get Language Model File Data  # noqa: E501
        """
        pass

    def test_get_language_models(self):
        """Test case for get_language_models

        Get Language Models  # noqa: E501
        """
        pass

    def test_train_language_model(self):
        """Test case for train_language_model

        Train Language Model  # noqa: E501
        """
        pass

    def test_update_language_model(self):
        """Test case for update_language_model

        Update Language Model  # noqa: E501
        """
        pass

    def test_update_language_model_file(self):
        """Test case for update_language_model_file

        Update Language Model file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
