# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import videoindexer
from videoindexer.api.person_models_api import PersonModelsApi  # noqa: E501
from videoindexer.rest import ApiException


class TestPersonModelsApi(unittest.TestCase):
    """PersonModelsApi unit test stubs"""

    def setUp(self):
        self.api = PersonModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_custom_face(self):
        """Test case for create_custom_face

        Create Custom Face  # noqa: E501
        """
        pass

    def test_create_person(self):
        """Test case for create_person

        Create Person  # noqa: E501
        """
        pass

    def test_create_person_model(self):
        """Test case for create_person_model

        Create Person Model  # noqa: E501
        """
        pass

    def test_delete_custom_face(self):
        """Test case for delete_custom_face

        Delete Custom Face  # noqa: E501
        """
        pass

    def test_delete_person(self):
        """Test case for delete_person

        Delete Person  # noqa: E501
        """
        pass

    def test_delete_person_model(self):
        """Test case for delete_person_model

        Delete Person Model  # noqa: E501
        """
        pass

    def test_get_custom_face_picture(self):
        """Test case for get_custom_face_picture

        Get Custom Face Picture  # noqa: E501
        """
        pass

    def test_get_custom_faces(self):
        """Test case for get_custom_faces

        Get Custom Faces  # noqa: E501
        """
        pass

    def test_get_custom_faces_sprite(self):
        """Test case for get_custom_faces_sprite

        Get Custom Faces Sprite  # noqa: E501
        """
        pass

    def test_get_person_models(self):
        """Test case for get_person_models

        Get Person Models  # noqa: E501
        """
        pass

    def test_get_persons(self):
        """Test case for get_persons

        Get Persons  # noqa: E501
        """
        pass

    def test_update_person(self):
        """Test case for update_person

        Update Person  # noqa: E501
        """
        pass

    def test_update_person_model(self):
        """Test case for update_person_model

        Update Person Model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
