# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import videoindexer
from videoindexer.api.indexing_api import IndexingApi  # noqa: E501
from videoindexer.rest import ApiException


class TestIndexingApi(unittest.TestCase):
    """IndexingApi unit test stubs"""

    def setUp(self):
        self.api = IndexingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_video_index(self):
        """Test case for get_video_index

        Get Video Index  # noqa: E501
        """
        pass

    def test_re_index_video(self):
        """Test case for re_index_video

        Re-Index Video  # noqa: E501
        """
        pass

    def test_upload_video(self):
        """Test case for upload_video

        Upload Video  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
