# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountMediaServicesAadConnectionContract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'str',
        'application_key': 'str'
    }

    attribute_map = {
        'application_id': 'applicationId',
        'application_key': 'applicationKey'
    }

    def __init__(self, application_id=None, application_key=None):  # noqa: E501
        """AccountMediaServicesAadConnectionContract - a model defined in Swagger"""  # noqa: E501
        self._application_id = None
        self._application_key = None
        self.discriminator = None
        self.application_id = application_id
        self.application_key = application_key

    @property
    def application_id(self):
        """Gets the application_id of this AccountMediaServicesAadConnectionContract.  # noqa: E501


        :return: The application_id of this AccountMediaServicesAadConnectionContract.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this AccountMediaServicesAadConnectionContract.


        :param application_id: The application_id of this AccountMediaServicesAadConnectionContract.  # noqa: E501
        :type: str
        """
        if application_id is None:
            raise ValueError("Invalid value for `application_id`, must not be `None`")  # noqa: E501

        self._application_id = application_id

    @property
    def application_key(self):
        """Gets the application_key of this AccountMediaServicesAadConnectionContract.  # noqa: E501


        :return: The application_key of this AccountMediaServicesAadConnectionContract.  # noqa: E501
        :rtype: str
        """
        return self._application_key

    @application_key.setter
    def application_key(self, application_key):
        """Sets the application_key of this AccountMediaServicesAadConnectionContract.


        :param application_key: The application_key of this AccountMediaServicesAadConnectionContract.  # noqa: E501
        :type: str
        """
        if application_key is None:
            raise ValueError("Invalid value for `application_key`, must not be `None`")  # noqa: E501

        self._application_key = application_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountMediaServicesAadConnectionContract, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountMediaServicesAadConnectionContract):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
