# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountMediaServicesUpdateContract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aad_connection': 'OneOfAccountMediaServicesUpdateContractAadConnection',
        'resource_group': 'str',
        'subscription_id': 'str'
    }

    attribute_map = {
        'aad_connection': 'aadConnection',
        'resource_group': 'resourceGroup',
        'subscription_id': 'subscriptionId'
    }

    def __init__(self, aad_connection=None, resource_group=None, subscription_id=None):  # noqa: E501
        """AccountMediaServicesUpdateContract - a model defined in Swagger"""  # noqa: E501
        self._aad_connection = None
        self._resource_group = None
        self._subscription_id = None
        self.discriminator = None
        if aad_connection is not None:
            self.aad_connection = aad_connection
        if resource_group is not None:
            self.resource_group = resource_group
        if subscription_id is not None:
            self.subscription_id = subscription_id

    @property
    def aad_connection(self):
        """Gets the aad_connection of this AccountMediaServicesUpdateContract.  # noqa: E501


        :return: The aad_connection of this AccountMediaServicesUpdateContract.  # noqa: E501
        :rtype: OneOfAccountMediaServicesUpdateContractAadConnection
        """
        return self._aad_connection

    @aad_connection.setter
    def aad_connection(self, aad_connection):
        """Sets the aad_connection of this AccountMediaServicesUpdateContract.


        :param aad_connection: The aad_connection of this AccountMediaServicesUpdateContract.  # noqa: E501
        :type: OneOfAccountMediaServicesUpdateContractAadConnection
        """

        self._aad_connection = aad_connection

    @property
    def resource_group(self):
        """Gets the resource_group of this AccountMediaServicesUpdateContract.  # noqa: E501


        :return: The resource_group of this AccountMediaServicesUpdateContract.  # noqa: E501
        :rtype: str
        """
        return self._resource_group

    @resource_group.setter
    def resource_group(self, resource_group):
        """Sets the resource_group of this AccountMediaServicesUpdateContract.


        :param resource_group: The resource_group of this AccountMediaServicesUpdateContract.  # noqa: E501
        :type: str
        """

        self._resource_group = resource_group

    @property
    def subscription_id(self):
        """Gets the subscription_id of this AccountMediaServicesUpdateContract.  # noqa: E501


        :return: The subscription_id of this AccountMediaServicesUpdateContract.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this AccountMediaServicesUpdateContract.


        :param subscription_id: The subscription_id of this AccountMediaServicesUpdateContract.  # noqa: E501
        :type: str
        """

        self._subscription_id = subscription_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountMediaServicesUpdateContract, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountMediaServicesUpdateContract):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
