# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnimatedCharacterInsightThumbnail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'id': 'str',
        'instances': 'list[InsightInstance]'
    }

    attribute_map = {
        'file_name': 'fileName',
        'id': 'id',
        'instances': 'instances'
    }

    def __init__(self, file_name=None, id=None, instances=None):  # noqa: E501
        """AnimatedCharacterInsightThumbnail - a model defined in Swagger"""  # noqa: E501
        self._file_name = None
        self._id = None
        self._instances = None
        self.discriminator = None
        if file_name is not None:
            self.file_name = file_name
        if id is not None:
            self.id = id
        if instances is not None:
            self.instances = instances

    @property
    def file_name(self):
        """Gets the file_name of this AnimatedCharacterInsightThumbnail.  # noqa: E501


        :return: The file_name of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this AnimatedCharacterInsightThumbnail.


        :param file_name: The file_name of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def id(self):
        """Gets the id of this AnimatedCharacterInsightThumbnail.  # noqa: E501


        :return: The id of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AnimatedCharacterInsightThumbnail.


        :param id: The id of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def instances(self):
        """Gets the instances of this AnimatedCharacterInsightThumbnail.  # noqa: E501


        :return: The instances of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :rtype: list[InsightInstance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this AnimatedCharacterInsightThumbnail.


        :param instances: The instances of this AnimatedCharacterInsightThumbnail.  # noqa: E501
        :type: list[InsightInstance]
        """

        self._instances = instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnimatedCharacterInsightThumbnail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnimatedCharacterInsightThumbnail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
