# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomPersonModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'is_default': 'bool',
        'name': 'str',
        'persons_count': 'int'
    }

    attribute_map = {
        'id': 'id',
        'is_default': 'isDefault',
        'name': 'name',
        'persons_count': 'personsCount'
    }

    def __init__(self, id=None, is_default=None, name=None, persons_count=None):  # noqa: E501
        """CustomPersonModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_default = None
        self._name = None
        self._persons_count = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if is_default is not None:
            self.is_default = is_default
        if name is not None:
            self.name = name
        if persons_count is not None:
            self.persons_count = persons_count

    @property
    def id(self):
        """Gets the id of this CustomPersonModel.  # noqa: E501


        :return: The id of this CustomPersonModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CustomPersonModel.


        :param id: The id of this CustomPersonModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def is_default(self):
        """Gets the is_default of this CustomPersonModel.  # noqa: E501


        :return: The is_default of this CustomPersonModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this CustomPersonModel.


        :param is_default: The is_default of this CustomPersonModel.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def name(self):
        """Gets the name of this CustomPersonModel.  # noqa: E501


        :return: The name of this CustomPersonModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomPersonModel.


        :param name: The name of this CustomPersonModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def persons_count(self):
        """Gets the persons_count of this CustomPersonModel.  # noqa: E501


        :return: The persons_count of this CustomPersonModel.  # noqa: E501
        :rtype: int
        """
        return self._persons_count

    @persons_count.setter
    def persons_count(self, persons_count):
        """Sets the persons_count of this CustomPersonModel.


        :param persons_count: The persons_count of this CustomPersonModel.  # noqa: E501
        :type: int
        """

        self._persons_count = persons_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomPersonModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomPersonModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
