# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Face(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'source_type': 'KnownPersonFaceSourceType',
        'source_video_id': 'str',
        'state': 'KnownPersonFaceState'
    }

    attribute_map = {
        'id': 'id',
        'source_type': 'sourceType',
        'source_video_id': 'sourceVideoId',
        'state': 'state'
    }

    def __init__(self, id=None, source_type=None, source_video_id=None, state=None):  # noqa: E501
        """Face - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._source_type = None
        self._source_video_id = None
        self._state = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if source_type is not None:
            self.source_type = source_type
        if source_video_id is not None:
            self.source_video_id = source_video_id
        if state is not None:
            self.state = state

    @property
    def id(self):
        """Gets the id of this Face.  # noqa: E501


        :return: The id of this Face.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Face.


        :param id: The id of this Face.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def source_type(self):
        """Gets the source_type of this Face.  # noqa: E501


        :return: The source_type of this Face.  # noqa: E501
        :rtype: KnownPersonFaceSourceType
        """
        return self._source_type

    @source_type.setter
    def source_type(self, source_type):
        """Sets the source_type of this Face.


        :param source_type: The source_type of this Face.  # noqa: E501
        :type: KnownPersonFaceSourceType
        """

        self._source_type = source_type

    @property
    def source_video_id(self):
        """Gets the source_video_id of this Face.  # noqa: E501


        :return: The source_video_id of this Face.  # noqa: E501
        :rtype: str
        """
        return self._source_video_id

    @source_video_id.setter
    def source_video_id(self, source_video_id):
        """Sets the source_video_id of this Face.


        :param source_video_id: The source_video_id of this Face.  # noqa: E501
        :type: str
        """

        self._source_video_id = source_video_id

    @property
    def state(self):
        """Gets the state of this Face.  # noqa: E501


        :return: The state of this Face.  # noqa: E501
        :rtype: KnownPersonFaceState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Face.


        :param state: The state of this Face.  # noqa: E501
        :type: KnownPersonFaceState
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Face, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Face):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
