# coding: utf-8

"""
    Operations

    The Operations API contains all the Azure Video Indexer APIs, like Upload video, Get insights and more, as well as authorization operations to get access tokens for calling the other operations. For Azure Resource Manager (ARM)-based accounts, some REST APIs like generating an access token, list of all accounts, and updating existing accounts <a href=\"https://aka.ms/avam-arm-api\" target=\"_blank\">can be found here</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VisualContentModerationInsight(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adult_score': 'float',
        'id': 'int',
        'instances': 'list[InsightInstance]',
        'racy_score': 'float'
    }

    attribute_map = {
        'adult_score': 'adultScore',
        'id': 'id',
        'instances': 'instances',
        'racy_score': 'racyScore'
    }

    def __init__(self, adult_score=None, id=None, instances=None, racy_score=None):  # noqa: E501
        """VisualContentModerationInsight - a model defined in Swagger"""  # noqa: E501
        self._adult_score = None
        self._id = None
        self._instances = None
        self._racy_score = None
        self.discriminator = None
        if adult_score is not None:
            self.adult_score = adult_score
        if id is not None:
            self.id = id
        if instances is not None:
            self.instances = instances
        if racy_score is not None:
            self.racy_score = racy_score

    @property
    def adult_score(self):
        """Gets the adult_score of this VisualContentModerationInsight.  # noqa: E501


        :return: The adult_score of this VisualContentModerationInsight.  # noqa: E501
        :rtype: float
        """
        return self._adult_score

    @adult_score.setter
    def adult_score(self, adult_score):
        """Sets the adult_score of this VisualContentModerationInsight.


        :param adult_score: The adult_score of this VisualContentModerationInsight.  # noqa: E501
        :type: float
        """

        self._adult_score = adult_score

    @property
    def id(self):
        """Gets the id of this VisualContentModerationInsight.  # noqa: E501


        :return: The id of this VisualContentModerationInsight.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VisualContentModerationInsight.


        :param id: The id of this VisualContentModerationInsight.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def instances(self):
        """Gets the instances of this VisualContentModerationInsight.  # noqa: E501


        :return: The instances of this VisualContentModerationInsight.  # noqa: E501
        :rtype: list[InsightInstance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this VisualContentModerationInsight.


        :param instances: The instances of this VisualContentModerationInsight.  # noqa: E501
        :type: list[InsightInstance]
        """

        self._instances = instances

    @property
    def racy_score(self):
        """Gets the racy_score of this VisualContentModerationInsight.  # noqa: E501


        :return: The racy_score of this VisualContentModerationInsight.  # noqa: E501
        :rtype: float
        """
        return self._racy_score

    @racy_score.setter
    def racy_score(self, racy_score):
        """Sets the racy_score of this VisualContentModerationInsight.


        :param racy_score: The racy_score of this VisualContentModerationInsight.  # noqa: E501
        :type: float
        """

        self._racy_score = racy_score

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VisualContentModerationInsight, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VisualContentModerationInsight):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
